### ISSUE TITLE
Set up Unity Project

### ISSUE THREAD

**Issue by AndGit-00** [travis-boyd/CSC492-How2#5]

**Comment by travis-boyd** [comment]
I've created a blank Unity project (Core 3D), using Unity Editor 2022.3.10f1, and added it to the repository.
I've also added Github's pre-made .gitignore file designed for Unity projects. This tells git to exclude from the repository everything in the Unity project except the directories that need to be shared. It excludes directories that are used by Unity itself and are created from the files that are included in the repo, and also excludes directories that contain local settings.
i referred to [this blog post](https://unityatscale.com/unity-version-control-guide/how-to-setup-unity-project-on-github/#adding-gitignore)
