### ISSUE TITLE
System – Design Perspective

### ISSUE THREAD

**Issue by AndGit-00** [travis-boyd/CSC492-How2#7]

**Comment by travis-boyd** [comment]
I'm proposing a term for the glossary: Quest
Like we've discussed, the design of the minigame is for two "tasks" for each level. I want to make it more clear that a "task" can consist of multiple "sub-tasks," so I propose the word "Quest" to mean the entire "Task." In other words, a minigame level will consists of two "Quests." 
In my Movement 101 example, the first level's "Quests" would be 1. "use WASD to walk around" and 2. "walk to a specific location on the map"
IMO this makes it more clear that, eg, in the Health 101 example, a single "Quest" could have a series of multiple directions that teach about each different type of health recovery options.

If this term is accepted, it means that our design for each minigame level will contain two written lessons, and two "Quests."
